version: '3.3'
services:
  images_server:
    image: nginx:alpine
    ports:
      - 8888:80
    volumes:
      - type: bind
        source: /home/ubuntu/web
        target: /usr/share/nginx/html
  project-backend:
    image: 592115514/se331-project-backend
    ports:
    - "8107:8080"